couchbase:
  bootstrap-servers: localhost
  bucketName: poc-mgen-2021-001
  bucketNameLoopback: poc-mgen-2021-002-loopback
  userName: Administrator
  password: password
kafka:
  bootstrap-servers: localhost:9092
  topic:
    csvInputTopic: POC_MGEN_COLLECT
    loopbackTopic: POC_MGEN_LOOPBACK
kafka-connect:
  input_files: /var/mgen-poc/files/input_files
  managed_files: /var/mgen-poc/files/managed_files
  rejected_files: /var/mgen-poc/files/rejected_files
  tasks_max: 0
  listing_interval: 5000
